CNN_LAYER_SETTINGS = [{'filters': 64, 'kernel_size': 7},{'filters': 32, 'kernel_size': 3}]
LATENT_DIM = 7
LOOKBACK = 15
DROPOUT_RATE = 0.07
EPOCHS = 25
BATCH_SIZE = 2048
POOL_SIZE = 2
N_TRAINING_SAMPLES = 50
LOSS = 'mse'